### ISSUE TITLE
Unable to load DLL 'oo2core_9_win64.dll' or one of its dependencies

### ISSUE THREAD

**Issue by maybecanel** [h4lfheart/FortnitePorting#24]
![image](https://github.com/halfuwu/FortnitePorting/assets/118028035/90341d73-5fd2-4dae-bc36-4ee11bbbe6f8)

**Comment by h4lfheart** [comment]
fixed in latest

**Comment by ryannorrington** [comment]
Hi, this error is still present in 1.5.4. On a first time install of 1.5.3, then an update to 1.5.4

`[17:05:19 ERR] System.DllNotFoundException: Unable to load DLL 'oo2core_9_win64.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at CUE4Parse.Compression.Oodle.OodleLZ_Decompress(Byte* buffer, Int64 bufferSize, Byte* output, Int64 outputBufferSize, Int32 a, Int32 b, Int32 c, Int64 d, Int64 e, Int64 f, Int64 g, Int64 h, Int64 i, Int32 threadModule)
   at CUE4Parse.Compression.Oodle.Decompress(Byte[] compressed, Int32 compressedOffset, Int32 compressedSize, Byte[] uncompressed, Int32 uncompressedOffset, Int32 uncompressedSize, FArchive reader)
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(FArchive archive)
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(Stream data, String name)
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(String path, String name)
   at CUE4Parse.MappingsProvider.UsmapTypeMappingsProvider.Load(String path)
   at CUE4Parse.MappingsProvider.FileUsmapTypeMappingsProvider..ctor(String path)
   at FortnitePorting.ViewModels.CUE4ParseViewModel.LoadLocalMappings()
   at FortnitePorting.ViewModels.CUE4ParseViewModel.InitializeMappings()
   at FortnitePorting.ViewModels.CUE4ParseViewModel.Initialize()
   at FortnitePorting.ViewModels.LoadingViewModel.<Initialize>b__3_0()
   at FortnitePorting.ViewModels.LoadingViewModel.Initialize()
   at FortnitePorting.Views.LoadingView.OnLoaded(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by Tevtongermany** [comment]
Warframe Probably degraded the oodle so just go to the fp discord server and ask for it there
